channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - click=8.1.7
  - contourpy=1.2.0
  - cycler=0.11.0
  - dill=0.3.7
  - editdistance=0.6.1
  - expat=2.5.0
  - filelock=3.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - huggingface_hub=0.20.3
  - imageio=2.33.1
  - intel-openmp=2023.1.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=3.1
  - nltk=3.8.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pandas=2.2.1
  - pillow=10.2.0
  - pip=23.3.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - rhash=1.4.3
  - scikit-plot=0.3.7
  - scipy=1.11.4
  - seaborn=0.12.2
  - sentencepiece=0.1.99
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tokenizers=0.15.1
  - tqdm=4.65.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - unidecode=1.2.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - attrs==23.2.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - cmake==3.28.4
      - cython==3.0.9
      - docker-pycreds==0.4.0
      - emoji==2.10.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - idna==3.6
      - jinja2==3.1.3
      - lit==18.1.2
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - protobuf==4.25.3
      - psutil==5.9.8
      - scikit-learn==1.4.1.post1
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - stanza==1.8.1
      - sympy==1.12
      - threadpoolctl==3.4.0
      - toml==0.10.2
      - torch==2.0.1
      - torch-geometric==2.4.0
      - triton==2.0.0
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - wandb==0.16.4
      - yarl==1.9.4
