model:
  num_hidden: 2000 # 128 # 1624 --> 3300 (for dropout)
  embedding_size: 2000 # 32 # 1624 --> 3300 (for dropout)
  num_heads: 16
  num_layers: 1
  dropout: 0.0 # 0.05 # 0.5

train:
  # device: 'cpu' # 'cuda' #'mps' or 'cuda' if high performance required else 'cpu'
  #  load: False
  #  save: False
  epochs: 2000 # 2000
  #  patience: 1177
  model_path: 'data/3_models/model'
  batch_size: 20000 # 8000

optimizer:
  learning_rate: 0.05 # 0.0005
  weight_decay: 0.0 # 0.00005 # 0.00005 # L2 regularization # 0.00001 < 0.00002 < 0.00005 > 0.0001 > 0.0005